### ISSUE TITLE
ImageFolder Plugin Constructor() could not be fired

### ISSUE THREAD

**Issue by TheGreatTaz** [TheLazySquid/DiscordImageFolder#13]
An error was encountered while trying to load this plugin.

```
TypeError: Cannot read properties of undefined (reading 'default')
    at new module.exports (betterdiscord://plugins/ImageFolder.plugin.js:75:93)
    at N.initializeAddon (betterdiscord/renderer.js:5:27014)
    at N.loadAddon (betterdiscord/renderer.js:5:6406)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)
```

**Comment by TheLazySquid** [comment]
Discord just pushed a big update that broke a lot of plugins, including this one. This should now be fixed, but you'll need to update it from this repo until the official repo accepts the changes.
