### ISSUE TITLE
More files error

### ISSUE THREAD

**Issue by bropines** [TheLazySquid/DiscordImageFolder#2]
I made symlinks to folders with pictures to simplify the work, but it seems the library didn’t like it.

This log error
```javascript
[2024-02-19 20:33:59.890][CONSOLE:ERROR] Menu API only allows Items and groups of Items as children. Received function _(e){return null} (object) instead
Error: Menu API only allows Items and groups of Items as children. Received function _(e){return null} (object) instead
    at https://discord.com/assets/41039.6778e3b66e0e5e4e0a2a.js:1:106514
    at Array.reduce (<anonymous>)
    at e (https://discord.com/assets/41039.6778e3b66e0e5e4e0a2a.js:1:105240)
    at T (https://discord.com/assets/41039.6778e3b66e0e5e4e0a2a.js:1:106723)
    at eval (betterdiscord://plugins/0BDFDB.plugin.js:2969:21)
    at ob (https://discord.com/assets/30550.01a5781bc8def3f12036.js:1:808076)
    at u (https://discord.com/assets/30550.01a5781bc8def3f12036.js:1:863286)
    at sI (https://discord.com/assets/30550.01a5781bc8def3f12036.js:1:846302)
    at https://discord.com/assets/30550.01a5781bc8def3f12036.js:1:846168
    at sN (https://discord.com/assets/30550.01a5781bc8def3f12036.js:1:846176)
    at sx (https://discord.com/assets/30550.01a5781bc8def3f12036.js:1:843261)
    at r6 (https://discord.com/assets/30550.01a5781bc8def3f12036.js:1:791951)
    at sE (https://discord.com/assets/30550.01a5781bc8def3f12036.js:1:843765)
    at https://discord.com/assets/30550.01a5781bc8def3f12036.js:1:871826
    at uu (https://discord.com/assets/30550.01a5781bc8def3f12036.js:1:871856)
    at t.render (https://discord.com/assets/30550.01a5781bc8def3f12036.js:1:875554)
    at MyReact.render (betterdiscord://plugins/0BDFDB.plugin.js:2953:40)
    at MyReact.hookCall (betterdiscord://plugins/0BDFDB.plugin.js:2968:23)
    at loadLibrary (betterdiscord://plugins/0BDFDB.plugin.js:7973:60)
    at parseData (betterdiscord://plugins/0BDFDB.plugin.js:1206:24)
    at parseCSS (betterdiscord://plugins/0BDFDB.plugin.js:1167:122)
    at requestLibraryData (betterdiscord://plugins/0BDFDB.plugin.js:1211:51)
    at eval (betterdiscord://plugins/0BDFDB.plugin.js:1157:7)
    at eval (betterdiscord://plugins/0BDFDB.plugin.js:222:56)
```
![image](https://github.com/TheLazySquid/DiscordImageFolder/assets/57861007/b70a5545-1bc8-45d8-a1b2-461a6a6be169)

If anything (if anyone is interested), I created symlinks like this:
Open CMD (Exactly CMD, PS does not know this cmdlet)
```
mklink /d "C:\Users\bropi\AppData\Roaming\BetterDiscord\plugins\imageFolder\name_symlink" "Path_to_your_folder"
```

**Comment by TheLazySquid** [comment]
I'm pretty sure that that error is unrelated to this plugin, looking at the stack trace it's coming from [BDFDB](https://betterdiscord.app/plugin/BDFDB). Assuming that the folders still work fine then I think it's safe to ignore it.

**Comment by bropines** [comment]
> I'm pretty sure that that error is unrelated to this plugin, looking at the stack trace it's coming from [BDFDB](https://betterdiscord.app/plugin/BDFDB). Assuming that the folders still work fine then I think it's safe to ignore it.

I didn’t write, the discord stupidly crashes when reading... The problem is this (I got so carried away with reading the logs that I forgot about the crashes)

**Comment by TheLazySquid** [comment]
As it turns out, this is an issue with electron's btoa function on very large strings as described [here](https://github.com/electron/electron/issues/8529). This means that regardless of the symlink, trying to load a high resolution image would cause a crash. I've switched it to useBuffer.from(...).toString('base64'), which is quite a bit slower, and loading several files causes a noticeable stutter. Hopefully this is just a temporary fix, and I can figure out a good way to load the images from disc without the lag in the near future.

**Comment by bropines** [comment]
I also noticed that if there are no images in the folder (text documents, for example) then here’s a joke
![image](https://github.com/TheLazySquid/DiscordImageFolder/assets/57861007/ace2dfcf-bb08-4a17-9118-d8e1352a4d9c)

**Comment by TheLazySquid** [comment]
Alright, in theory everything should now be working. Non-images shouldn't be broken, and I've made improvements to the image loading to hopefully make it faster, not freeze discord and (at least in theory) not crash. Additionally, images now aren't loaded until they enter the viewport which should mean that large image folders will run smoothly.

**Comment by TheLazySquid** [comment]
Make sure you're using v0.2.0 (which you'll need to download manually, since BetterDiscord hasn't accepted it yet). I managed to get several hundred images working without any real problems.

**Comment by bropines** [comment]
Well, now everything works (it seems perfect), the maximum note is that on my theme the button displaces the send button. I’ll probably close the issue, because we have achieved all our goals
![image](https://github.com/TheLazySquid/DiscordImageFolder/assets/57861007/2590a385-a513-4769-bdad-969b323afea7)
